<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class BarangSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'PCode'        => 'BRG001',
                'NamaLengkap'  => 'Indomie Goreng',
                'NamaStruk'    => 'Indomie Goreng',
                'NamaInitial'  => 'IG',
                'SatuanSt'     => 'PCS',
                'Barcode1'     => '8992388101015',
                'Harga1c'      => 3500.00, // Harga Jual
                'Harga1b'      => 2800.00, // Harga Beli
                'HargaBeli'    => 2800,
                'HPP'          => 2800,
                'Status'       => 'T',
                'FlagReady'    => 'Y',
                'AddDate'      => date('Y-m-d H:i:s'),
                'EditDate'     => date('Y-m-d H:i:s'),
            ],
            [
                'PCode'        => 'BRG002',
                'NamaLengkap'  => 'Teh Botol Sosro 450ml',
                'NamaStruk'    => 'Teh Botol',
                'NamaInitial'  => 'TBS',
                'SatuanSt'     => 'BTL',
                'Barcode1'     => '8992745100015',
                'Harga1c'      => 4500.00,
                'Harga1b'      => 3500.00,
                'HargaBeli'    => 3500,
                'HPP'          => 3500,
                'Status'       => 'T',
                'FlagReady'    => 'Y',
                'AddDate'      => date('Y-m-d H:i:s'),
                'EditDate'     => date('Y-m-d H:i:s'),
            ],
            [
                'PCode'        => 'BRG003',
                'NamaLengkap'  => 'Beras Premium 5kg',
                'NamaStruk'    => 'Beras 5kg',
                'NamaInitial'  => 'BP5',
                'SatuanSt'     => 'SAK',
                'Barcode1'     => '8993451234567',
                'Harga1c'      => 65000.00,
                'Harga1b'      => 58000.00,
                'HargaBeli'    => 58000,
                'HPP'          => 58000,
                'Status'       => 'T',
                'FlagReady'    => 'Y',
                'AddDate'      => date('Y-m-d H:i:s'),
                'EditDate'     => date('Y-m-d H:i:s'),
            ],
            [
                'PCode'        => 'BRG004',
                'NamaLengkap'  => 'Minyak Goreng Tropical 2L',
                'NamaStruk'    => 'Minyak 2L',
                'NamaInitial'  => 'MG2',
                'SatuanSt'     => 'BTL',
                'Barcode1'     => '8992831234098',
                'Harga1c'      => 32000.00,
                'Harga1b'      => 28000.00,
                'HargaBeli'    => 28000,
                'HPP'          => 28000,
                'Status'       => 'T',
                'FlagReady'    => 'Y',
                'AddDate'      => date('Y-m-d H:i:s'),
                'EditDate'     => date('Y-m-d H:i:s'),
            ],
            [
                'PCode'        => 'BRG005',
                'NamaLengkap'  => 'Gula Pasir Premium 1kg',
                'NamaStruk'    => 'Gula 1kg',
                'NamaInitial'  => 'GP1',
                'SatuanSt'     => 'KG',
                'Barcode1'     => '8991234567890',
                'Harga1c'      => 15000.00,
                'Harga1b'      => 12500.00,
                'HargaBeli'    => 12500,
                'HPP'          => 12500,
                'Status'       => 'T',
                'FlagReady'    => 'Y',
                'AddDate'      => date('Y-m-d H:i:s'),
                'EditDate'     => date('Y-m-d H:i:s'),
            ],
            [
                'PCode'        => 'BRG006',
                'NamaLengkap'  => 'Aqua Botol 600ml',
                'NamaStruk'    => 'Aqua 600ml',
                'NamaInitial'  => 'AQ6',
                'SatuanSt'     => 'BTL',
                'Barcode1'     => '8998888888888',
                'Harga1c'      => 3000.00,
                'Harga1b'      => 2200.00,
                'HargaBeli'    => 2200,
                'HPP'          => 2200,
                'Status'       => 'T',
                'FlagReady'    => 'Y',
                'AddDate'      => date('Y-m-d H:i:s'),
                'EditDate'     => date('Y-m-d H:i:s'),
            ],
            [
                'PCode'        => 'BRG007',
                'NamaLengkap'  => 'Kopi Kapal Api 165gr',
                'NamaStruk'    => 'Kopi KA 165gr',
                'NamaInitial'  => 'KKA',
                'SatuanSt'     => 'PCK',
                'Barcode1'     => '8992745678901',
                'Harga1c'      => 18000.00,
                'Harga1b'      => 15000.00,
                'HargaBeli'    => 15000,
                'HPP'          => 15000,
                'Status'       => 'T',
                'FlagReady'    => 'Y',
                'AddDate'      => date('Y-m-d H:i:s'),
                'EditDate'     => date('Y-m-d H:i:s'),
            ],
            [
                'PCode'        => 'BRG008',
                'NamaLengkap'  => 'Susu Ultra Milk Coklat 1L',
                'NamaStruk'    => 'Ultra Coklat 1L',
                'NamaInitial'  => 'UMC',
                'SatuanSt'     => 'PCS',
                'Barcode1'     => '8992745111222',
                'Harga1c'      => 18500.00,
                'Harga1b'      => 16000.00,
                'HargaBeli'    => 16000,
                'HPP'          => 16000,
                'Status'       => 'T',
                'FlagReady'    => 'Y',
                'AddDate'      => date('Y-m-d H:i:s'),
                'EditDate'     => date('Y-m-d H:i:s'),
            ],
            [
                'PCode'        => 'BRG009',
                'NamaLengkap'  => 'Chitato Rasa Sapi Panggang 68gr',
                'NamaStruk'    => 'Chitato SP 68gr',
                'NamaInitial'  => 'CHT',
                'SatuanSt'     => 'PCK',
                'Barcode1'     => '8992388333444',
                'Harga1c'      => 12000.00,
                'Harga1b'      => 9500.00,
                'HargaBeli'    => 9500,
                'HPP'          => 9500,
                'Status'       => 'T',
                'FlagReady'    => 'Y',
                'AddDate'      => date('Y-m-d H:i:s'),
                'EditDate'     => date('Y-m-d H:i:s'),
            ],
            [
                'PCode'        => 'BRG010',
                'NamaLengkap'  => 'Sabun Lifebuoy 85gr',
                'NamaStruk'    => 'Lifebuoy 85gr',
                'NamaInitial'  => 'LFB',
                'SatuanSt'     => 'PCS',
                'Barcode1'     => '8999999123456',
                'Harga1c'      => 4500.00,
                'Harga1b'      => 3500.00,
                'HargaBeli'    => 3500,
                'HPP'          => 3500,
                'Status'       => 'T',
                'FlagReady'    => 'Y',
                'AddDate'      => date('Y-m-d H:i:s'),
                'EditDate'     => date('Y-m-d H:i:s'),
            ],
            [
                'PCode'        => 'BRG011',
                'NamaLengkap'  => 'Telur Ayam Negeri 1kg',
                'NamaStruk'    => 'Telur 1kg',
                'NamaInitial'  => 'TAN',
                'SatuanSt'     => 'KG',
                'Barcode1'     => '8991111222333',
                'Harga1c'      => 28000.00,
                'Harga1b'      => 25000.00,
                'HargaBeli'    => 25000,
                'HPP'          => 25000,
                'Status'       => 'T',
                'FlagReady'    => 'Y',
                'AddDate'      => date('Y-m-d H:i:s'),
                'EditDate'     => date('Y-m-d H:i:s'),
            ],
            [
                'PCode'        => 'BRG012',
                'NamaLengkap'  => 'Rinso Detergen 900gr',
                'NamaStruk'    => 'Rinso 900gr',
                'NamaInitial'  => 'RNS',
                'SatuanSt'     => 'PCK',
                'Barcode1'     => '8998888777666',
                'Harga1c'      => 22000.00,
                'Harga1b'      => 18500.00,
                'HargaBeli'    => 18500,
                'HPP'          => 18500,
                'Status'       => 'T',
                'FlagReady'    => 'Y',
                'AddDate'      => date('Y-m-d H:i:s'),
                'EditDate'     => date('Y-m-d H:i:s'),
            ],
        ];

        // Insert data
        $this->db->table('masterbarang')->insertBatch($data);

        echo "\n✅ Master Barang created: 12 items\n";
    }
}
